---
- hosts: localhost
  connection: local
  vars:
    cvx_secure_logging: false

    SKU_level:
      dev:
       sku_level: "S2"      
      test:
       sku_level: "S2"
      prod:
       sku_level: "S2"  
    
  roles:
    # basic app service test..
    - role: ansible-role-azure-asp
      azure_asp_autoscale_metricname: CpuPercentage
      azure_asp_autoscale_statistic: Average
      azure_asp_autoscale_timeaggregation: Average
      azure_asp_autoscale_scaleup_operator: GreaterThan 
      azure_asp_autoscale_scaleup_timegrain: PT10M
      azure_asp_autoscale_scaleup_timewindow: PT1H
      azure_asp_autoscale_scaleup_threshold: 80
      azure_asp_autoscale_scaleup_value: 1
      azure_asp_autoscale_scaleup_cooldown: PT15M
      azure_asp_autoscale_scaledown_operator: LessThan
      azure_asp_autoscale_scaledown_timegrain: PT10M
      azure_asp_autoscale_scaledown_timewindow: PT1H
      azure_asp_autoscale_scaledown_threshold: 50
      azure_asp_autoscale_scaledown_value: 1
      azure_asp_autoscale_scaledown_cooldown: PT15M
      azure_asp_sku: "{{ SKU_level[cvx_environment_name].sku_level}}"
      azure_asp_name: tcobt-{{ cvx_environment_name }}-frontend-linux-cvx
      azure_asp_is_linux: true
    - role: ansible-role-azure-app-service
      azure_app_service_name: "{{ cvx_mnemonic }}-frontend-{{ cvx_environment_name }}"
      azure_app_service_asp_name: tcobt-{{ cvx_environment_name }}-frontend-linux-cvx
      azure_app_service_zip_deploy_enabled: true
      azure_app_service_bind_dns: false
      azure_app_service_client_cert_enabled: false
      azure_app_service_register_dns: false
      azure_app_service_type: "linux"
      azure_app_service_cert_mode: "Optional"
      azure_app_service_node_version: '18.3.0'
      azure_app_service_linux_runtime_stack: "NODE|22-lts"
      azure_app_service_startup_command: "pm2 serve /home/site/wwwroot/browser --spa --no-daemon"
      azure_app_service_cors_allow_credentials: true
      azure_app_service_auth_enabled: false
      azure_app_service_bind_dns: true
      azure_app_service_register_dns: true
      azure_app_service_fqdn: 'lpgbid-{{ cvx_environment_name }}.tengizchevroil.com'
      azure_app_service_custom_hostnames: 
        - 'lpgbid-{{ cvx_environment_name }}.tengizchevroil.com'
      azure_app_service_angular_app_settings:
        - name: clientId
          value: "{{ '58a40fb4-a4a5-4a4d-b75b-1f9a312d9480' if cvx_environment_name=='prod' else 'd4b7eadd-4b7d-406b-9a87-94f0199bcd5f' }}"
        - name: redirectUri
          value: "https://tcobid-frontend-{{ cvx_environment_name }}.azurewebsites.net"
        - name: oidcScopes
          value: "https://tcobid-{{ cvx_environment_name }}.azure.chevron.com/user_impersonation"
        - name: graphScopes
          value: [ "User.Read", "User.Read.All"]
        - name: autoSignIn
          value: true
        - name: popupForLogin
          value: true
        - name: cacheLocation
          value: "localStorage"
        - name: instance
          value: "https://login.microsoftonline.com/"
        - name: tenantId
          value: "fd799da1-bfc1-4234-a91c-72b3a1cb9e26"
      azure_app_service_bind_dns: true
    - role: ansible-role-azure-app-service-bindcertificate
      azure_app_service_name: "{{ cvx_mnemonic }}-frontend-{{ cvx_environment_name }}"
      azure_app_service_asp_name: tcobt-{{ cvx_environment_name }}-frontend-linux-cvx
      azure_app_service_custom_hostnames: 
       - 'lpgbid-{{ cvx_environment_name }}.tengizchevroil.com'     