export const TABLE_COLUMNS = {
  DEFAULT_USER: [
    {
      id: "asseT_NUMBER_BK",
      label: "Asset number",
      width: 150,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 1,
    },
    {
      id: "equipmenT_TAG",
      label: "Equipment tag",
      width: 180,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 2,
    },
    {
      id: "enrichmenT_ASSIGN_TO",
      label: "Assigned to enrichment",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 3,
    },
    {
      id: "walkdowN_ASSIGN_TO",
      label: "Assigned to field verification",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 4,
    },
    {
      id: "equipmenT_STATUS",
      label: "Enrichment status",
      width: 150,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 5,
    },
    {
      id: "equipmenT_TAG_DESCRIPTION",
      label: "Description EN",
      width: 180,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 6,
    },
    {
      id: "equipmenT_TAG_DESCRIPTION_RU",
      label: "Description RU",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 7,
    },
     {
      id: "jdE_CLASSIFICATION",
      label: "Class",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 8,
    },
    {
      id: "jdE_SUBCLASSIFICATION",
      label: "Sub-class",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 9,
    },
    {
      id: "jdE_STATUS",
      label: "Status",
      width: 100,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 10,
    },
    {
      id: "pid",
      label: "PID",
      width: 160,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 11,
    },
     {
      id: "manufacturer",
      label: "Manufacturer",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 12,
    },
    {
      id: "equipmenT_MODEL_NUMBER",
      label: "Model",
      width: 200,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 13,
    },
    {
      id: "seriaL_NUMBER",
      label: "Serial number",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 14,
    },
    {
      id: "parenT_EQUIPMENT_TAG",
      label: "Parent tag",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 15,
    },
    {
      id: "eC_RANKING",
      label: "Equipment criticality",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 16,
    },
    {
      id: "aC_RANKING",
      label: "Asset criticality",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 17,
    },
    {
      id: "iC_RANKING",
      label: "Integrity criticality",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 18,
    },
    {
      id: "comment",
      label: "Comment",
      width: 200,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 19,
    },
    {
      id: "syS_CODE",
      label: "System group",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 20,
    },
    {
      id: "planT_SECTION",
      label: "Plant section",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 21,
    },
    {
      id: "planT_FACILITY",
      label: "Plant/facility",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 22,
    },
    // {
    //   id: "details",
    //   label: "Details",
    //   width: 100,
    //   isVisible: false,
    //   isChecked: true,
    //   isDisabled: true,
    //   align: "center",
    //   order: 23,
    // },
  ],
  SME_USER: [
    {
      id: "asseT_NUMBER_BK",
      label: "Asset number",
      width: 150,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 1,
    },
    {
      id: "equipmenT_TAG",
      label: "Equipment tag",
      width: 180,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 2,
    },
    {
      id: "enrichmenT_ASSIGN_TO",
      label: "Assigned to enrichment",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 3,
    },
    {
      id: "walkdowN_ASSIGN_TO",
      label: "Assigned to field verification",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 4,
    },
    {
      id: "equipmenT_STATUS",
      label: "Enrichment status",
      width: 150,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 5,
    },
    {
      id: "equipmenT_TAG_DESCRIPTION",
      label: "Description EN",
      width: 180,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 6,
    },
    {
      id: "equipmenT_TAG_DESCRIPTION_RU",
      label: "Description RU",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 7,
    },
     {
      id: "jdE_CLASSIFICATION",
      label: "Class",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 8,
    },
    {
      id: "jdE_SUBCLASSIFICATION",
      label: "Sub-class",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 9,
    },
    {
      id: "jdE_STATUS",
      label: "Status",
      width: 100,
      isVisible: true,
      isChecked: true,
      isDisabled: true,
      align: "left",
      order: 10,
    },
    {
      id: "pid",
      label: "PID",
      width: 160,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 11,
    },
     {
      id: "manufacturer",
      label: "Manufacturer",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 12,
    },
    {
      id: "equipmenT_MODEL_NUMBER",
      label: "Model",
      width: 200,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 13,
    },
    {
      id: "seriaL_NUMBER",
      label: "Serial number",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 14,
    },
    {
      id: "parenT_EQUIPMENT_TAG",
      label: "Parent tag",
      width: 180,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 15,
    },
    {
      id: "eC_RANKING",
      label: "Equipment criticality",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 16,
    },
    {
      id: "aC_RANKING",
      label: "Asset criticality",
      width: 140,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 17,
    },
    {
      id: "iC_RANKING",
      label: "Integrity criticality",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 18,
    },
    {
      id: "comment",
      label: "Comment",
      width: 200,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 19,
    },
    {
      id: "syS_CODE",
      label: "System group",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 20,
    },
    {
      id: "planT_SECTION",
      label: "Plant section",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 21,
    },
    {
      id: "planT_FACILITY",
      label: "Plant/facility",
      width: 100,
      isVisible: true,
      isChecked: false,
      isDisabled: false,
      align: "left",
      order: 22,
    },
    // {
    //   id: "details",
    //   label: "Details",
    //   width: 100,
    //   isVisible: false,
    //   isChecked: true,
    //   isDisabled: true,
    //   align: "center",
    //   order: 23,
    // },
  ]
}

export const DEFAULT_JDE_COLUMNS = TABLE_COLUMNS.DEFAULT_USER.toSorted(
  (a, b) => a.order - b.order
);

export const SME_USER_JDE_COLUMNS = TABLE_COLUMNS.SME_USER.toSorted(
  (a, b) => a.order - b.order
);

export const TABLE_COLUMNS_IN_FILTER = [
  {
    id: "equipmenT_TAG",
    value: "equipmenT_TAG",
    label: "Equipment Tag",
  },
  {
    id: "parenT_EQUIPMENT_TAG",
    value: "parenT_EQUIPMENT_TAG",
    label: "Parent Tag",
  },
  {
    id: "jdE_CLASSIFICATION",
    value: "jdE_CLASSIFICATION",
    label: "Class",
  },
  {
    id: "jdE_SUBCLASSIFICATION",
    value: "jdE_SUBCLASSIFICATION",
    label: "Sub-class",
  },
  {
    id: "equipmenT_TAG_DESCRIPTION",
    value: "equipmenT_TAG_DESCRIPTION",
    label: "Description EN",
  },
  {
    id: "equipmenT_TAG_DESCRIPTION_RU",
    value: "equipmenT_TAG_DESCRIPTION_RU",
    label: "Description RU",
  },
  {
    id: "manufacturer",
    value: "manufacturer",
    label: "Manufacturer",
  },
  {
    id: "seriaL_NUMBER",
    value: "seriaL_NUMBER",
    label: "Serial number",
  },
  {
    id: "asseT_NUMBER_BK",
    value: "asseT_NUMBER_BK",
    label: "Asset number",
  },
  {
    id: "equipmenT_MODEL_NUMBER",
    value: "equipmenT_MODEL_NUMBER",
    label: "Model",
  },
  {
    id: "pid",
    value: "pid",
    label: "PID",
  },
  {
    id: "aC_RANKING",
    value: "aC_RANKING",
    label: "Asset criticality",
  },
  {
    id: "eC_RANKING",
    value: "eC_RANKING",
    label: "Equipment criticality",
  },
  {
    id: "walkdowN_ASSIGN_TO",
    value: "walkdowN_ASSIGN_TO",
    label: "Assigned to field verification",
  },
  {
    id: "enrichmenT_ASSIGN_TO",
    value: "enrichmenT_ASSIGN_TO",
    label: "Assigned to enrichment",
  },
  {
    id: "syS_CODE",
    value: "syS_CODE",
    label: "System group",
  },
  {
    id: "planT_SECTION",
    value: "planT_SECTION",
    label: "Plant section",
  },
  {
    id: "jdE_STATUS",
    value: "jdE_STATUS",
    label: "Status",
  },
  {
    id: "planT_FACILITY",
    value: "planT_FACILITY",
    label: "Plant/Facility",
  },
  {
    id: "iC_RANKING",
    value: "iC_RANKING",
    label: "Integrity criticality",
  },
  {
    id: "equipmenT_STATUS",
    value: "equipmenT_STATUS",
    label: "Enrichment status",
  },
  {
    id: "comment",
    value: "comment",
    label: "Comment",
  },
];

export const EQUIPMENT_GENERAL_CHAR_NAME = {
  ASSET_NUMBER: "ASSET_NUMBER",
  MAN_SERIAL_NUMBER: "MAN_SERIAL_NUMBER",
  PARENT_EQUIPMENT_TAG: "PARENT_EQUIPMENT_TAG",
  MANUFACTURER: "MANUFACTURER",
  EQUIPMENT_TAG_DESCRIPTION: "EQUIPMENT_TAG_DESCRIPTION",
  PID: "PID",
  MODELNO: "MODELNO",
  CRITICALITY: "CRITICALITY",
  EQUIPMENT_TAG: "EQUIPMENT_TAG",
  EC_RANKING: "EC_RANKING",
  AC_RANKING: "AC_RANKING",
  IC_RANKING: "IC_RANKING",
  JDE_STATUS: "JDE_STATUS",
  EQUIPMENT_TAG_DESCRIPTION_EN: "EQUIPMENT_TAG_DESCRIPTION_EN",
  EQUIPMENT_TAG_DESCRIPTION_RU: "EQUIPMENT_TAG_DESCRIPTION_RU",
  JDE_CLASSIFICATION: "JDE_CLASSIFICATION",
  JDE_SUBCLASSIFICATION: "JDE_SUBCLASSIFICATION",
};

export const EQUIPMENT_CHARS_MAP = {
  ASSET_NUMBER: "Asset number",
  EQUIPMENT_TAG: "Equipment tag",
  EQUIPMENT_TAG_DESCRIPTION_EN: "Description EN",
  EQUIPMENT_TAG_DESCRIPTION_RU: "Description RU",
  JDE_CLASSIFICATION: "Class",
  JDE_SUBCLASSIFICATION: "Sub-class",
  JDE_STATUS: "Status",
  PID: "PID",
  MANUFACTURER: "Manufacturer",
  MODELNO: "Model number",
  MAN_SERIAL_NUMBER: "Serial number",
  PARENT_EQUIPMENT_TAG: "Parent tag",
  EC_RANKING: "Equipment criticality",
  AC_RANKING: "Asset criticality",
  IC_RANKING: "Integrity criticality",
};

export const ORDERED_EQUIPMENT_CHARS = [
  "ASSET_NUMBER",
  "EQUIPMENT_TAG",
  "EQUIPMENT_TAG_DESCRIPTION_EN",
  "EQUIPMENT_TAG_DESCRIPTION_RU",
  "JDE_CLASSIFICATION",
  "JDE_SUBCLASSIFICATION",
  "JDE_STATUS",
  "PID",
  "MANUFACTURER",
  "MODELNO",
  "MAN_SERIAL_NUMBER",
  "PARENT_EQUIPMENT_TAG",
  "EC_RANKING",
  "AC_RANKING",
  "IC_RANKING",
];

export const ONLY_JDE_EQUIPMENT_CHARS = [
  "ASSET_NUMBER",
  "EQUIPMENT_TAG_DESCRIPTION",
  "CRITICALITY",
  "EC_RANKING",
  "AC_RANKING",
  "IC_RANKING",
];

export const ATTRIBUTES_OPTIONAL_FIELDS = [
  "MANUFACTURER",
  "MODELNO",
  "JDE_STATUS",
  "MAN_SERIAL_NUMBER",
  "ASSET_NUMBER",
  "IC_RANKING",
  "AC_RANKING",
  "EC_RANKING",
];

export const FILTER_PARAMS = {
  CATEGORY_ID: "CategoryId",
  CLASS_ID: "ClassId",
  SUBCLASS_ID: "SubClassId",
  AREA_CODE: "AreaCode",
  UNIT_CODE: "UnitCode",
  FILTERED_COLUMS: "FilteredColums",
  SEARCH: "Search",
};

export const TABLE_COLUMN_LABELS = {
  equipmenT_TAG: "Equipment tag",
  manufacturer: "Manufacturer",
  seriaL_NUMBER: "Serial number",
  asseT_NUMBER_BK: "Asset number",
  equipmenT_MODEL_NUMBER: "Model",
  pid: "PID",
  parenT_EQUIPMENT_TAG: "Parent tag",
  equipmenT_TAG_DESCRIPTION: "Description EN",
  equipmenT_TAG_DESCRIPTION_RU: "Description RU",
  aC_RANKING: "Asset criticality",
  eC_RANKING: "Equipment criticality",
  syS_CODE: "System group",
  planT_SECTION: "Plant section",
  jdE_STATUS: "Status",
  planT_FACILITY: "Plant/Facility",
  constructioN_YEAR_MONTH: "Construction year month",
  iC_RANKING: "Integrity criticality",
  equipmenT_STATUS: "Enrichment status",
  comment: "Comment",
  details: "Details",
  walkdowN_ASSIGN_TO: "Assigned to field verification",
  enrichmenT_ASSIGN_TO: "Assigned to enrichment",
  jdE_CLASSIFICATION: "Class",
  jdE_SUBCLASSIFICATION: "Sub-class",
};

export const CRITICALITY_OPTIONS = [
  {
    label: "Low",
    value: "Low",
  },
  {
    label: "Normal",
    value: "Normal",
  },
  {
    label: "Critical",
    value: "Critical",
  },
  {
    label: "Not applicable",
    value: "Not applicable",
  },
];

export const GENERAL_STATUS_OPTIONS = [
  {
    value: "DN",
    label: "DN",
  },
  {
    value: "DM",
    label: "DM",
  },
  {
    value: "AV",
    label: "AV",
  },
];

export const MANUFACTURER_STATUS = {
  NEW: "New",
  JDE_E1_ORIGINAL: "JDE E1 original",
};

export const OPERATOR = [
  {
    value: "=",
    label: "Equals",
  },
  {
    value: "%",
    label: "Contains",
  },
  {
    value: "%S",
    label: "Starts With",
  },

  {
    value: "%E",
    label: "Ends With",
  },
  {
    value: "%E",
    label: "Greater than",
  },
  {
    value: "%E",
    label: "Less than",
  },
];

export const FILENAME = "JDE data";

export const IMG_DELETE_ALLOWED_STATUSES = [
  "JDE E1 Original",
  "Review by LTI",
  "Completed by LTI",
  "Review by DS",
  "Review by FV",
  "Review by Archive",
  "Return to DS",
  "Return to FV",
  "Internal QA/QC",
];
