trigger:
  branches:
    include:
      - release

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    REPO_URL="https://$(AZURE_DEVOPS_USER):$(AZURE_DEVOPS_PAT)@dev.azure.com/chevron/TCO-FINANCE-GovernmentConnectPortal/_git/TCO-FINANCE-GovernmentConnectPortal-Frontend"

    echo "Fetching the latest commit from the release branch..."
    git fetch $REPO_URL release
    LATEST_COMMIT=$(git rev-parse FETCH_HEAD)

    echo "Delete the old latest-stable tag if it exists.."
    git tag -d latest-stable || true
    git push $REPO_URL :refs/tags/latest-stable || true

    echo "Creating the new latest-stable tag..."
    git tag latest-stable $LATEST_COMMIT

    echo "Pushing the new latest-stable tag to the remote repos..."
    git push $REPO_URL latest-stable
    
  displayName: 'Update latest stable tag'
