---
- hosts: localhost
  connection: local
  vars:
    azure_DAST_secure_logging: false
  roles:
  - role: ansible-role-dast-netsparker
    dast_profile_name: 'CICD - TCO Facilities Integrity and Reliability Management - Website - 1 - profile'
    dast_target_uri: 'https://dcam-test.tengizchevroil.com/'
    